# .github/workflows/test.yml
name: Ruby Gem Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2 # Specify the Ruby version you're using
        bundler-cache: true # Cache the gems for faster builds

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rspec
